return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "c",
      "json",
      "javascript",
      "typescript",
      "tsx",
      "html",
      "css",
      "lua",
      "markdown",
      "java",
      "python",
      "vim",
      "gitignore",
      "dockerfile",
      "bash",
    },
    sync_install = false,
    highlight = { enable = true },
    indent = { enable = false },
  },
}
